server:
  port: 1008
#spring.profiles.active=local
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ms-practice
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
